const Song = require('../entity/Song');

exports.fromModelToEntity = (
  {
    id,
    title,
    albumTitle,
    artist,
    albumArtist,
    compositor,
    genre,
    lyrics,
    lyricist,
    trackNumber,
    year,
    comment,
    audioFile,
    cover,
    albumId,
    createdAt = null,
    updatedAt = null,
    Album,
  },
  fromAlbumModelToEntityMapper,
) =>
  new Song(
    Number(id),
    title,
    albumTitle,
    artist,
    albumArtist,
    compositor,
    genre,
    lyrics,
    lyricist,
    Number(trackNumber),
    Number(year),
    comment,
    audioFile,
    cover,
    albumId,
    createdAt,
    updatedAt,
    Album ? fromAlbumModelToEntityMapper(Album) : {},
  );

exports.fromFormToEntity = ({
  id,
  title,
  'album-title': albumTitle,
  artist,
  'album-artist': albumArtist,
  compositor,
  genre,
  lyrics,
  lyricist,
  'track-number': trackNumber,
  year,
  comment,
  'audio-file': audioFile,
  cover,
  'created-at': createdAt,
}) =>
  new Song(
    id,
    title,
    albumTitle,
    artist,
    albumArtist,
    compositor,
    genre,
    lyrics,
    lyricist,
    trackNumber,
    year,
    comment,
    audioFile,
    cover,
    createdAt,
  );
